theme: jekyll-theme-minimal
title: Plumber Component Decorator for Sitecore Commerce
description: Make components viewable and editable in Sitecore Commerce Business Tools
logo: /images/plumber-logo284x284.png

